dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov coverage nose

script:
  - nosetests --with-coverage --cover-package=skutil

after_success:
  - codecov